//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundCollection
    {
        public int ID { get; set; }
        public string FundName { get; set; }
        public Nullable<System.DateTime> FundInceptionDate { get; set; }
        public Nullable<double> FundExpenseRatio { get; set; }
    }
}
